ENV APACHE_CONFDIR /etc/apache2
ENV APACHE_ENVVARS $APACHE_CONFDIR/envvars

COPY docker-php-setup-apache apache2-foreground /usr/local/bin/
RUN env APACHE_FPM=1 docker-php-setup-apache

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		runit \
	&& rm -rf /var/lib/apt/lists/*

ENV PHP_EXTRA_CONFIGURE_ARGS --enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi
