{{ include "version-id" -}}
WORKDIR /var/www/html

COPY docker-php-setup-fpm /usr/local/bin/
RUN env \
	{{ if (.version | version_id) >= ("7.3" | version_id) then "REMOVE_LOG_DECORATION=1" else "" end }} \
	docker-php-setup-fpm

# Override stop signal to stop process gracefully
# https://github.com/php/php-src/blob/17baa87faddc2550def3ae7314236826bc1b1398/sapi/fpm/php-fpm.8.in#L163
STOPSIGNAL SIGQUIT

EXPOSE 9000
