#!/bin/bash
set -eux

apt-get update
apt-get install -y --no-install-recommends apache2
rm -rf /var/lib/apt/lists/*

# generically convert lines like
#   export APACHE_RUN_USER=www-data
# into
#   : ${APACHE_RUN_USER:=www-data}
#   export APACHE_RUN_USER
# so that they can be overridden at runtime ("-e APACHE_RUN_USER=...")
sed -ri 's/^export ([^=]+)=(.*)$/: ${\1:=\2}\nexport \1/' "$APACHE_ENVVARS"

# setup directories and permissions
. "$APACHE_ENVVARS"
for dir in \
	"$APACHE_LOCK_DIR" \
	"$APACHE_RUN_DIR" \
	"$APACHE_LOG_DIR" \
; do
	rm -rvf "$dir"
	mkdir -p "$dir"
	chown "$APACHE_RUN_USER:$APACHE_RUN_GROUP" "$dir"
# allow running as an arbitrary user (https://github.com/docker-library/php/issues/743)
	chmod 777 "$dir"
done

# delete the "index.html" that installing Apache drops in here
rm -rvf /var/www/html/*

# logs should go to stdout / stderr
ln -sfT /dev/stderr "$APACHE_LOG_DIR/error.log"
ln -sfT /dev/stdout "$APACHE_LOG_DIR/access.log"
ln -sfT /dev/stdout "$APACHE_LOG_DIR/other_vhosts_access.log"
chown -R --no-dereference "$APACHE_RUN_USER:$APACHE_RUN_GROUP" "$APACHE_LOG_DIR"

# Apache + PHP requires preforking Apache for best results
if [ ! -z ${APACHE_FPM+x} ]; then
	a2enmod mpm_event proxy_fcgi
else
	a2dismod mpm_event && a2enmod mpm_prefork
fi

# PHP files should be handled by PHP, and should be preferred over any other file type
{
		echo '<FilesMatch \.php$>'
if [ ! -z ${APACHE_FPM+x} ]; then
		echo '\tSetHandler proxy:unix:/var/run/php-fpm/fpm.sock|fcgi://localhost/'
else
		echo '\tSetHandler application/x-httpd-php'
fi
		echo '</FilesMatch>'
		echo
		echo 'DirectoryIndex disabled'
		echo 'DirectoryIndex index.php index.html'
		echo
		echo '<Directory /var/www/>'
		echo '\tOptions -Indexes'
		echo '\tAllowOverride All'
		echo '</Directory>'
} | tee "$APACHE_CONFDIR/conf-available/docker-php.conf" \
&& a2enconf docker-php
